### PR TITLE
Align publish workflow with other plugins

### PR DESCRIPTION
**Pull request by pat-s**
And maybe also fix the fact that images for the most recent releases are missing on DH.

### CODE REVIEW

**Review by anbraten — APPROVED** [review]

**Comment by 6543** [comment]
@pat-s well it looks good but we still got an issue: https://ci.woodpecker-ci.org/repos/6032/pipeline/915

**Comment by 6543** [comment]
the branch info is alright:
image

**Comment by 6543** [comment]
sorry we missed some regressions:
- ddd0e5489bbc838aae4bb1b5e3a9f45a8048286a
- 7a373ba3e7beadfba01a2f7d927905f53a8cf02e

**Comment by pat-s** [comment]
1.2.0 still didn't get published on DH: https://hub.docker.com/r/woodpeckerci/plugin-s3/tags

**Pull request merged**
